#!/bin/sh
# Quickly set a new Eo version.
# Usage: setversion <version>
# e.g.   setversion 1.0

NEW_VERSION=$1

# make sure version is not empty
if [ -z "$NEW_VERSION" ]; then
    echo "Error: No new version specified"
    exit
fi

eoversion() 
{
 grep 'EO_VERSION :=' source/eo.ooc | grep -o '[0-9.]\{1,\}'
}

EO_VERSION=$(eoversion)
echo "Current version: $EO_VERSION"

REPL="s/$EO_VERSION/$NEW_VERSION/"
echo "sed replacement command: $REPL"
echo "After change:"
sed -i.bak $REPL source/eo.ooc | grep 'EO_VERSION :='

git commit source/eo.ooc -m "version $NEW_VERSION"
git tag $NEW_VERSION
git push --all
git push --tags

