#!/bin/sh
# Quickly set a new Eo version.
# Usage: setversion <version>
# e.g.   setversion 1.0

# TODO: check if there are uncommitted git changes; if so, complain & exit

NEW_VERSION=$1

# make sure version is not empty
if [ -z "$NEW_VERSION" ]; then
    echo "Error: No new version specified"
    exit
fi

git_status()
{
 git status --porcelain | grep -m 1 "^ [MADRCU]" 
}

UNSAVED_CHANGES=$(git_status)
if [ ! -z "$UNSAVED_CHANGES" ]; then
    echo "Error: unsaved changes; add/commit first"
    exit
fi

exit

eoversion() 
{
 grep 'EO_VERSION :=' source/eo.ooc | grep -o '[0-9.]\{1,\}'
}

EO_VERSION=$(eoversion)
echo "Current version: $EO_VERSION"

REPL="s/$EO_VERSION/$NEW_VERSION/"
echo "sed replacement command: $REPL"
echo "After change:"
sed -i.bak $REPL source/eo.ooc | grep 'EO_VERSION :='

git commit source/eo.ooc -m "version $NEW_VERSION"
git tag $NEW_VERSION
git push --all
git push --tags

